Mobile menu branch
suthish777/Personal-portfolio pull request #8
Opened 2023-05-15 15:48 UTC by suthish777

I and my coding partner together completed this project,
we created the mobile menu for the portfolio website.

2023-05-15 16:49 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)


# Hi @suthish777 👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title ✔

## Required Changes ♻️
- _Check the comments under the review._
- you just have to make a few changes and you're on your way 🚀.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-15 16:49 UTC, AbelG101 commented on main.js
> +});
- [ ] It seems like there's a bug in this code as the mobile menu isn't appearing when the menu Icon is clicked. Please make sure to fix this. ✔
- Here's the bug:
    ![image](https://github.com/suthish777/Personal-portfolio/assets/104968236/9452ba21-75fc-4d3f-a422-62e07c476084)
    - I think instead of using the `className()` method you're looking for `classList.toggle()` method as that works. 😉

2023-05-15 16:49 UTC, AbelG101 commented on index.html
https://github.com/suthish777/Personal-portfolio/blob/c231380df3d34f461669492ecb4dd84f76677429/index.html#L72-L89
- [ ] It seems like you're repeating the above landing page section two times and it's disrupting the UI please make sure to remove one of them.
- Here's how it looks currently:
  ![firefox_94riHv6vVT](https://github.com/suthish777/Personal-portfolio/assets/104968236/33b24847-5fc6-47ba-ab57-2454d7ddeb08)
- [ ] Also please make sure the hamburger menu button disappears and the proper desktop version of the landing page is displayed when the screen is resized. ✔

2023-05-16 04:17 UTC, christianbiring1 approved these changes
Hi @suthish777 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 

## Highlights
- [ ] Great job on implementing the hamburger menu and the user can interact with it as they are supposed to.
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] DesvriptivE PR `title` and `summary` :+1: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-16 04:17 UTC, christianbiring1 approved these changes
Hi @suthish777 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 

## Highlights
- [ ] Great job on implementing the hamburger menu and the user can interact with it as they are supposed to.
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] DesvriptivE PR `title` and `summary` :+1: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-16 07:57 UTC, merged